name: CI

on:
# Postsubmit CI on main.
  push:
    branches: [main]
  # Presubmit CI on PRs to all branches.
  pull_request:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    # - name: Install dotnet-format tool
    #   run: dotnet tool install -g dotnet-format

    # - name: Verify dotnet format
    #   run: cd src && dotnet format --verify-no-changes --verbosity diagnostic

    - name: Restore dependencies
      run: cd src && dotnet restore

    - name: Build
      run: cd src && dotnet build --no-restore

    # - name: Unit Tests
    #   run: dotnet test
