name: .NET Core

on:
  release:
    types: [created]
    name: Release

jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Build
        shell: bash
        run: |
          release_name=Auth-Sample
          unset CI
          # Build everything
          dotnet publish ./ -c Release -o "$release_name"

          7z a -tzip "auth-sample.zip" "./${release_name}/*"

          # Delete output directory
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "auth-sample.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
